# Generated by Django 2.2.3 on 2019-07-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedimage',
            name='age',
            field=models.IntegerField(default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postedimage',
            name='email',
            field=models.CharField(default='example@.a', max_length=64),
            preserve_default=False,
        ),
    ]
