# Generated by Django 2.2.3 on 2019-08-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190715_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedimage',
            name='age',
            field=models.IntegerField(),
        ),
    ]
